### PR TITLE
make eval just eval rather than creating a new repl for each one

### LINKED ISSUE #79: It is possible to just eval in CLJS and not create a new REPL for each evaluation
This code details how its possible to just have an eval and not have to do a full cljs-repl boot for each evaluation.

The functions highlighted below only need to be evaluated with cljs.env/*compliler* bound.

https://github.com/bhauman/rebel-readline/blob/master/rebel-readline-cljs/src/rebel_readline/cljs/service/local.clj#L57-L79

This will speed up the evaluation significantly and as a bonus simplify things so that we can evaluate all the sent forms and provide interrupt to get the prompt back.

This is a very straightforward fix. 
@cemerick ^

### PR DESCRIPTION
**Pull request by bhauman**
fixes #79

### CODE REVIEW

**Comment by bhauman** [comment]
OK now I'm looking at the tests

**Comment by bhauman** [comment]
If you run lein test you will see that all tests are passing on nashorn.

Travis seems to be having a fundamental build problem.

There is one test failing for rhino and that is the printing test. I'm not sure what is going on there.

**Comment by bhauman** [comment]
well the printing test does not work for rhino. But, when I use Rhino at the REPL printing works just fine so I'm going to chalk that up to a difficult testing environment.

**Comment by bhauman** [comment]
I'm going to call this finished except for fixing the test somehow.

**Comment by bbatsov** [comment]
@bhauman Do you plan to cut a new release for this change soon? I think that'd be pretty cool.

**Comment by bbatsov** [comment]
> well the printing test does not work for rhino. But, when I use Rhino at the REPL printing works just fine so I'm going to chalk that up to a difficult testing environment.

I wonder if anyone wants a rhino REPL at all - maybe we can just drop the ugly code around it and point people in the direction of nashorn.

**Pull request merged**
